### PR TITLE
Relax deps

### PR DESCRIPTION
**Pull request by bertsky**

### CODE REVIEW

**Comment by bertsky** [comment]
I still cannot run the initial example though – it complains with 
```
loadManifestURLsFromPickle:62 - Keine Datei misc/bsb_newspapers_01.pkl gefunden und keine IIIF-Collection URL übergeben.
```

**Comment by bertsky** [comment]
Seeing your upstream changes (commenting out convert_ocr instead of my try-catch), I wonder why Github does not sound the alarm my version cannot be merged without conflict...

**Comment by karkraeg** [comment]
> I still cannot run the initial example though – it complains with
> 
> ```
> loadManifestURLsFromPickle:62 - Keine Datei misc/bsb_newspapers_01.pkl gefunden und keine IIIF-Collection URL übergeben.
> ```

should be fixed with https://github.com/karkraeg/iiimets/commit/c71b2365202e68d68d4634a3a4689209dd2b4598

**Comment by karkraeg** [comment]
we should skip the hOCR Download and hOCR to ALTO conversion for now; I uncommented the usage of those functions in https://github.com/karkraeg/iiimets/blob/c71b2365202e68d68d4634a3a4689209dd2b4598/iiimets.py#L3

**Pull request merged**
